### ISSUE TITLE
Build instructions to install seq as codon plugin.

### ISSUE THREAD

**Issue by ghuls** [exaloop/seq#2]
Are there somewhere build instructions on how to install seq as codon plugin?

**Comment by inumanag** [comment]
Working on it—will be out soon!

**Comment by ghuls** [comment]
@inumanag Any update on this?

**Comment by inumanag** [comment]
@ghuls Sorry, still working on this one.

For now, you can at least do:
```
<clone seq>
cmake -S . -B build -G Ninja -DLLVM_DIR=<exaloop LLVM dir> -DCODON_PATH=<location of codon installation> -DCMAKE_BUILD_TYPE=Release
cmake --install build --prefix <path_to_codon>/lib/codon/plugins/seq
```

Then you can run Codon as

```
codon run -plugin seq code.codon ...
```

There are still some occasional issues with `build` mode in release mode on Linux that need to be fixed.

**Comment by inumanag** [comment]
Hi @ghuls 

I have just refactored out quite a few things and simplified the build process. Also, `codon build -plugin seq` does not have any dependencies anymore.

See https://github.com/0xTCG/biser/blob/master/Dockerfile for details. We will merge the changes into codon-master soon.

**Comment by ghuls** [comment]
The Docker fille needs a small change (master instead of codon).
```
STEP 17/21: RUN git clone -b codon https://github.com/0xTCG/biser /github/biser
Cloning into '/github/biser'...
fatal: Remote branch codon not found in upstream origin
Error: error building at STEP "RUN git clone -b codon https://github.com/0xTCG/biser /github/biser": error while running runtime: exit status 128
```

**Comment by inumanag** [comment]
You can ignore that part--- it is BISER related; the steps above are for Codon/Seq :)

**Comment by f0t1h** [comment]
Any updates on this?

**Comment by inumanag** [comment]
I have just pushed Seq binaries and instructions in README. Let me know if something is amiss.
